# file to explore data
# reads the same pickle as generated by data_parser.py
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

import pickle

def read_sample_data_from_pickle(fname):
    with open(fname, 'rb') as rf:
        bb_list, targets_list = pickle.load(rf)
    return bb_list[0].astype(np.float32), targets_list[0].astype(np.float32)

def show_precision_distribution(nparr, max_prec=20):
    n_distinct = []
    for precision in range(max_prec):
        rounded = np.round(nparr, decimals=precision)
        targets_df = pd.DataFrame(rounded, columns=['x', 'y'])
        grouped = targets_df.groupby(['x', 'y'])['x'].count()
        n_distinct.append(len(grouped))

    plt.plot(range(max_prec), n_distinct)

    # annotate the plot with labels of the actual numbers https://stackoverflow.com/a/22272358/10372825
    for prec, n_distinct in enumerate(n_distinct):
        plt.annotate(f"{prec}, {n_distinct}", xy=(prec, n_distinct), textcoords='data')
    plt.show()

def show_heatmap(nparr):
    plt.hist2d(*nparr.transpose(), bins=30)
    plt.show()


if __name__ == '__main__':
    bb, targets = read_sample_data_from_pickle('./data/FennData_20190125_Reshaped_30ms_cell_new.mat.minR2_0-nChan_40.pkl')


    print(bb.shape, targets.shape)

    show_heatmap(targets)
    show_precision_distribution(targets)
